### PR TITLE
Adding cck lights to common filters.cfg

### PR DESCRIPTION
**Pull request by Fengist**
I hope I did this right.  Sorry if I screwed it up.  I'm a GitNoob

IgorZ and I will be using CCK for our light mods.  The proposed changes are the addition of 2 icons and the addition of an Item in the common-filters.cfg

### CODE REVIEW

**Comment by BobPalmer** [comment]
Guys... there's a dev branch for a reason.

**Comment by ihsoft** [comment]
It would be helpful to have the process described in a readme. Different people follow the different approaches on how the pull requests and releases are done. E.g. in this case the pull request could go into the `develop` branch. And what's next? What steps are to be done to have the development branch be released?

**Comment by BobPalmer** [comment]
At this point, it makes more sense to have a single source for releases vs. several, and follow a protocol similar to what I have for CRP... which is discussion, pull requests to dev, then coordination of a release date.  Especially since (like CRP) there's rarely a need for an immediate hotfix.

**Comment by ihsoft** [comment]
Let's verify if I got it correctly (sorry, I'm not familiar to the process in CRP):
* _[Author of the feature]_ Propose and discuss a feature on the forum.
* _[Author of the feature]_ Get an informal approval and file a pull request into the `DEVELOP` branch.
* _[CCK owner]_ review and merge the pull request into `DEVELOP`.
* _[CCK owner or collaborator]_ Make a release on the coordinated date, if there is one, or within a month from the last release, otherwise.
  * On release the pull request in `master` should be merged from `DEVELOP`.

If yes, I'll add it into `SOURCE/CCK/README.md`.

And just a side note. Specifically for the mods that are not updated frequently, the "multi-point release" approach may be a benefit. For the mods like `CCK` it would take months before enough changes are accumulated. E.g. version `2.0.1` went out a half a year ago! Given there is a commit, what would be the rationale to wait before doing the release? And for how long?

**Comment by BobPalmer** [comment]
Close.

- [Author of the feature] Propose and discuss a feature or new filter on the forum.
- [Author of the feature] Get an informal approval and file a pull request into the DEVELOP branch.
- [CCK owner] review and merge the pull request into DEVELOP.
- [CCK owner] On the coordinated date, merge from DEVELOP to MASTER and publish a release.

**Comment by BobPalmer** [comment]
Also - I strongly disagree with a utility mod like this having releases without specific new content.  In a mod like this, it's a beneficial feature if the version remains the same for as long a period as possible, and tbh new features should be fairly rare.  I count it as a very good thing that we've had the same version for over half a year.

**Comment by ihsoft** [comment]
Got it.

Out of curiosity, what can the collaborators do? If any :)

**Pull request merged**
