### PR TITLE
Turn CCK into API

### PR DESCRIPTION
**Pull request by ihsoft**
I'd like to propose a major change to the CCK concept. In particular, turning it from "a kit" into "an API". Any third-party mod will be able to use CCK for easy and straightforward creation of a custom category. As long as authors choose to clone own independent tags we (as CCK maintainers) don't care - people just use CCK to save some lines of code. Though, having an ability to re-use CCK they may wish to cooperate with other authors and adopt existing/create new common categories since for them it will be a zero efforts migration.

When we decide to add a new common category the only thing we'll do is adding another `AddFilter` line in `Filters.cs`. And there will be no need for the other authors to do synchronous update in their mods due to `FilterManager` handles duplicates.

### CODE REVIEW

**Comment by ihsoft** [comment]
FYI. In spite of I have the permissions to do the merge I'd like to hear your feedback before doing it. It's a rather big change. Please, let me know if you think this change should or should not go to CCK. In the latter case I can move it into [KSPDev_Utils](https://github.com/ihsoft/KSPDev/tree/master/Sources/Utils).

**Comment by ihsoft** [comment]
And saying about adoption. There is MKS category "Kolonization" which may be also a good candidate for some KKAOSS parts. If both mods were using new API ability then user experience would be very solid: parts related to a colony on the surface of a planet are located in the same category. In spite of the fact each mod treats category `cck-kolonization` (name is a fiction) as own custom one :)

**Comment by Nils277** [comment]
Generally it is a good idea to make the CCK more modular and accessible.
But i'm not quite sure if i understand the concept correctly yet. Should each mod author who wants to make use of CCK refer to this plugin in their code and call the _AddFilter_ function to add their own category?

Wouldn't other mod authors still have to update their mods for the latest version of CCK when a new category was agreed upon? At least there needs to be a new common icon. It looks like it is possible to add icons outside of the CCK directory but when multiple authors add the same category but use a different icon, there will be at least a bit of confusion for some users when the icon for the same category changes depending on which mod comes to add its definition first. 

I'm not the biggest fan of having to add a 'third party mod' as a dependency to the plugin code of your own mod. Especially for new releases of KPS it might come to unwanted delays because mod authors have to wait for the new version of CCK to be able to update their plugin.

Therefore i would suggest another approach to amke it possible to add new categories through config files. e.g.:

```
CCKFilterConfig
{
    name = Containers
    tag = cck-containers
    fallbackIcon= MyMod/Containers
}
```
The fallback icon is only used when CKK finds no icon with the given name in its own icon folder.
This way, the mods can remain independent of CCK. Mod authors would still have to update when a new common icon is added to CCK though.

**Comment by JPLRepo** [comment]
I only have given this a cursory glance.. but I am not following what this proposal is and why?
..and unfortunately do not have the time to look at the code right now.
Does this change actually change the way a mod uses this kit?

and also, I did notice straight away in the 10 secs I flicked through the change that it's using Linq.
Which is not good for Unity performance and I would steer well clear of.

**Comment by BobPalmer** [comment]
Linq is not something you want to run every frame.  CCK runs once on startup so I expect the relatively few allocations (which would be cleared on the next GC) won't kill us in this particular application :D

**Comment by BobPalmer** [comment]
Not opposed to having this have the capability to work as an API, with a pre-established and agreed to set of options - since what it sounds like (and I need to dig more as well) is that it just opens it up for extension.  Would agree with @Nils277 that something where it can be added to via .cfg files may be the best way to go

**Comment by Nils277** [comment]
Coo, so what should these options be?
I think **tag** and **name** and **icon** are the obvious ones. What else migh be useful?

Question is, how should it be handled when two mods want to use the same tag but define a different  icon and/ or name for the same tag when there is no default in CCK?

**Comment by BobPalmer** [comment]
@Nils277 - good questions.  I agree w/tag, name, icon (basically the same stuff we need to pass to the method anyway).  Maybe a hybrid, with a collection of curated options (Life Support for example), that take precedence over config parsing.  Just to keep people from accidentally breaking it ;)

**Comment by ihsoft** [comment]
Thanks for the feedback, guys.

@Nils277 The original idea was to have modders calling `AddFilter` which will indeed require a dependency on the CCK assembly. Moving it into config sounds like a good idea since no binary deps will be needed. As for inconsistency with icons this problems will stay even with configs but it can be avoided by simply sorting the names, I'll add it.

@JPLRepo The idea is to convince people to stop people using custom approach every time they want a new category created in the editor. By giving them an API we convince modders to make first step towards the generic solution: using common categories that are shared between multiple mods. And if we really want it to work we should make it as easy as possible for the mod author to use.

**Comment by ihsoft** [comment]
How about extra field `usedByMod` in the item config? It will be useful for the new modders who will be deciding if they want using CCK.
```
CCKFilterConfig
{
  Item
  {
    name = Containers
    tag = cck-containers
    usedByMod = Kerbal Inventory System (KIS)
    usedByMod = Kerbal Attachment System (KAS)
  }
  Item
  {
    name = Life Support
    tag = cck-lifesupport
    usedByMod = USI Life Support
  }
}
```

**Comment by ihsoft** [comment]
Did the changes. In nutshell:
- Read common and extra filters from the config files:
  - To introduce a new common filter no real code needs to be changed. Just update `common-filters.cfg`.
  - Common filters _cannot_ be overridden. I.e. once we decide to turn a filter into "common" it will always appear as we've designed it.
  - Third-party mods modify `extra-filters.cfg` via `ModuleManager` (I'm going to make a Wiki page but for now comments in the file should be enough). A possible inconsistency with icons is addressed by sorting filter title. As long as mods set is not changed in the game the filter name/icon won't change in the editor.
  - I was thinking about adding common filters from the code instead of using config file but eventually decided it's not a good approach. A common filters config file has enough warnings in comments to stop people from mangling with it. On the other side, it gives a good background on how CCK does work.
- Icons moved into `icons` folder.
- Allow simple icons that only have normal texture. Omit `selectedIcon` field when it's the case.

Please, take another look.

**Comment by ihsoft** [comment]
Hey! If there are no objections I'll do the merge on Dec 1. Please, stop me if you don't like the approach :)

**Comment by ihsoft** [comment]
FYI. Here is an example of how third-parrty mod can intorduce own filter:
```
@CCKExtraFilterConfig
{
	Item
	{
		name = Kerbal Attachment System
		tag = cck-kas
		normalIcon = KAS-1.0/Textures/KASFilterIcon
		usedByMod = Kerbal Attachment System (KAS) v1.0
	}
}
```
I actually like this approach to create filters for KIS/KAS parts. Otherwise, I'd create them from the native code.

**Pull request merged**
